name: CI and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show directory contents
        run: ls -R

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 src tests

      - name: Run tests
        run: |
          pip install pytest
          pytest -s tests

      - name: Train model
        run: python src/train.py

      - name: Run inference
        run: python src/inference.py

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      YC_SA_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
      YC_OAUTH_TOKEN: ${{ secrets.YC_OAUTH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Yandex CLI and configure Docker
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          export PATH="$HOME/yandex-cloud/bin:$PATH"
          echo "$YC_SA_KEY" > key.json

          yc config profile create default
          yc config set service-account-key key.json
          yc config set cloud-id b1gor6e9ehbjpml7fkgt
          yc config set folder-id b1g5dm8gb8lh0uqgu8pd

          yc container registry configure-docker
          echo "${YC_OAUTH_TOKEN}" | docker login cr.yandex --username oauth --password-stdin

      - name: Check if token is set
        run: |
          if [ -z "$YC_OAUTH_TOKEN" ]; then
            echo "OAuth token is not set"
            exit 1
          else
            echo "OAuth token is present"
          fi

      - name: Build Docker image
        run: |
          set -euxo pipefail
          docker build -t cr.yandex/crp12lag013pmq95r5ij/summerpractice-app:latest .

      - name: Push Docker image
        run: |
          set -euxo pipefail
          docker push cr.yandex/crp12lag013pmq95r5ij/summerpractice-app:latest

      - name: Deploy to Yandex Serverless Container
        run: |
          set -euxo pipefail
          yc serverless container revision deploy \
            --container-name summerpractice-app \
            --image cr.yandex/crp12lag013pmq95r5ij/summerpractice-app:latest \
            --memory 512m \
            --cores 1 \
            --core-fraction 100 \
            --execution-timeout 30s \
            --concurrency 1 \
            --service-account-id ajent4a551erqtnobakv
